sources:
  - name: raw
    description: Raw data from CSV files
    database: postgres
    schema: raw

    tables:
      - name: census_2016_g01
      - name: census_2016_g02
      - name: listings
      - name: nsw_code
      - name: nsw_suburb